#nombre bd
spring.application.name=taskmanager

#spring.datasource.url=jdbc:h2:mem:taskdb
#h2 es una base de datos entre "" temporal
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#driver para bases de datos h2 de prueba que nos da spring
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#esto nos da una consola web para ver la base de datos en linea 
#spring.h2.console.path=/h2-console

